version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: datcord_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datcord_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

